[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  GATSBY_API_BASE_URL = "https://openstackid-resources.openstack.org"  
  GATSBY_SPONSORED_PROJECT_ID = "3"  
  GATSBY_HOME_SUBPROJECT_ID = "13"
  GATSBY_MEMBERS_SUBPROJECT_ID = "13"
[[redirects]]
  from = "/baidu"
  to = "/collateral/ApplicationOfKataContainersInBaiduAICloud.pdf"
[[redirects]]
  from = "/baiducn"
  to = "/collateral/Kata Containers在百度智能云的应用实践.pdf"
[[redirects]]
  from = "/blog"
  to = "https://medium.com/kata-containers"
  status = 301
  force = true
[[redirects]]
  from = "https://get.katacontainers.io"
  to = "https://raw.githubusercontent.com/kata-containers/kata-containers/main/utils/kata-manager.sh"
  status = 301
  force = true
