backend:
  name: github
  repo: OpenStackweb/kata-netlify-refresh
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://auth.katacontainers.io
publish_mode: editorial_workflow
media_folder: "site/.vuepress/public/images"
public_folder: "/images"
collections:

  - name: "main-pages"
    label: "Main Pages"
    editor:
      preview: false

    files:
      - label: "Home Page"
        name: "home-page"
        file: "site/index.md"
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: "headline", name: headline, widget: string }
              - label: Button
                name: button
                widget: object
                fields:
                  - { label: "title", name: title, widget: string }
                  - { label: "url", name: url, widget: string }
          - label: Values
            name: values
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Copy", name: copy, widget: text }
          - label: Get Involved Steps
            name: getInvolvedSteps
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Entry", name: entry, widget: text }
              - fields:
                  label: "Link"
                  name: link
                  widget: object
                  fields:
                    - { label: "URL", name: url, widget: string }
                    - { label: "Title", name: title, widget: string }
          - label: Body
            name: body
            widget: markdown

      - label: "Learn"
        name: "learn"
        file: "site/learn/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Software"
        name: "software"
        file: "site/software/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "FAQ"
        name: "faq"
        file: "site/faq/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Community"
        name: "community"
        file: "site/community/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

      - label: "Supporters"
        name: "supporters"
        file: "site/supporters/index.md"

        fields:
          - { label: "Description", name: description, widget: string }
          - { label: "Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Top Navigation"
        name: "topnav"
        file: "site/pages.json"
        fields:
          - label: Pages
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }

      - label: "Footer Navigation"
        name: "footernav"
        file: "site/footer-nav.json"
        fields:
          - label: About
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Connect
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
          - label: Software
            name: nav
            widget: list
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }
